sonar.projectKey=ui-library
sonar.projectName=UI Library
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.{js,jsx,ts,tsx}
sonar.exclusions=**/node_modules/**,**/*.spec.{js,jsx,ts,tsx}
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
